### ISSUE TITLE
styles not rendering properly on server with fresh clone

### ISSUE THREAD

**Issue by PTC-JoshuaMatthews** [fulls1z3/universal#59] opened 2017-08-16 18:06 UTC
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
After cloning the repo, doing npm install, then build then serve, there is a style difference between the server rendered initial view and the client rendered view once it passes over. 

**Expected/desired behavior**
views from server and client should use same styles

**Minimal reproduction of the problem with instructions**

clone repo, run the project as is, look at font changing on the initial load

**What is the motivation / use case for changing the behavior?**
Need consistent styles between browser and server

**Please tell us about your environment:**
VS Code, windows 10, node 6.9.1

* **Angular version:** 2.0.X
All package versions unchanged from clone

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 all 

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by fulls1z3** [comment] 2017-08-17 09:34
@PTC-JoshuaMatthews that's a duplicate of #15, and we're currently working on it as well as tracking the updates from Angular.

**Closed as completed by fulls1z3** 2017-08-17 09:34 UTC
Labels: duplicate

**Comment by PTC-JoshuaMatthews** [comment] 2017-08-17 18:57
@fulls1z3  But #15 is closed... is the issue moved somewhere else? 

Also they seem to be talking about a flicker, but what I am seeing is that server global imported styles are not applied at all, not just a flicker when it hands over rendering to the client. It makes my pages stylesless since no bootstrap css on the server rendered pages.  Is the flicker issue they are referring to really that bad?

**Comment by ChrisDalley** [comment] 2017-08-24 21:24
@fulls1z3 @PTC-JoshuaMatthews - I am seeing a similar issue where certain styles are not being rendered on the server side, not just a simple screen flicker between multiple renders. It looks like certain styles are either missing or mis-ordered on the page rendered by the server though I need to look into it properly over the next day or two. Could possibly be a difference in the webpack config for server vs browser?

**Comment by ChrisDalley** [comment] 2017-08-24 21:42
Scratch that, after looking a little deeper mine seems to be a separate issue with image urls in the scss which are getting rewritten into a load of jibberish on the server side that then stops any css after the url in the scss from being loaded related to #40
