### ISSUE TITLE
after update to Angular 5 unable to make build with `prod` or `stage`

### ISSUE THREAD

**Issue by sarfarazansari** [fulls1z3/universal#242] opened 2017-12-05 12:11 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**

Unable to make the build with `stage` or `prod` both mode (spa or universal)

**Expected/desired behavior**

It should be build because it is working fine in case of `dev` both mode (spa or universal)

**Minimal reproduction of the problem with instructions**
![image](https://user-images.githubusercontent.com/3416989/33606399-5abaddc0-d9e3-11e7-9a5b-0566b1c46f0f.png)

**What is the motivation / use case for changing the behavior?**

**Environment**
* **Angular version:** X.Y.Z

* **Browser:**
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

* **For Tooling issues:**
- Node version: v8.9.1
- Platform:  Mac

* Others:

**Comment by fulls1z3** [comment] 2017-12-05 12:20
Duplicate of #241

**Closed as completed by fulls1z3** 2017-12-05 12:20 UTC
Labels: duplicate
